### ISSUE TITLE
GridManager 常见问题汇总

### ISSUE THREAD

**Issue by baukh789** [baukh789/GridManager#144]
### 快速、灵活的对Table标签进行实例化，让Table标签充满活力。
> 希望`GridManager`提升了你的开发体验，也请将`GridManager`推荐给其他人。

#### API上存在的属性或方法，自已配置后却不生效?
可以通过 GM.version 查看 GridManager 版本号；如版本号与主站版本存在差异，请重新下载新版本进行尝试.

#### 数据在渲染前就已经存在,如何配置?
通过ajaxData参数进行配置, 需要注意的是: 这种方式下ajaxBeforeSend、ajaxError、ajaxComplete 将失效，仅有 ajaxSuccess 会被执行.

#### 如何在数据请求中增加筛选条件?
可以通过参数query进行配置,该参数会在 GirdManager 实例中一直存在,并且可以在筛选条件更改后通过 GridManager.setQuery(gridManagerName) 方法进行重置。

#### 开发中想查看当前的 GirdManager 实例中的数据怎么实现?
通过 GridManager.get(gridManagerName) 方法可以获得完整的GirdManager对象;

#### 实例化出错怎么办?
- 查看DOM节点是否为 table标签。
- 检查配置项gridManagerName是否存在或重复
- 检查配置项 columnData 中 key 值是否存在或重复。
- 检查配置项ajaxData配置是否正确。

#### 后端语言返回的数据格式与插件格式不同怎么处理?
可以通过参数dataKey(ajax请求返回的列表数据key键值,默认为data), totalsKey(ajax请求返回的数据总条数key键值,默认为totals)进行配置。

#### 表格th中的文本显示不全
查看配置项[ columnData ]中的 width , 将该值提高或不进行设置由插件自动控制. 如果还未生效,那是由于当前实例开始了记忆功能;
清除记忆方法: 将 localStorage 中包含与当前表格 grid-manager 名称对应的项清除,或使用 GridManager.clear() 将记忆全部清除。

#### 某一例配置的宽度为100px, 而生成的宽度却不是100px，并且出现了横向滚动条?
这是因为该列的文本实际所占宽度超出了100px, 可以将宽度配置到合理值或不设置宽度交由GridManager自动控制。
GridManager 对宽度进行配置时, 会参照当前列th文本的实际宽度值. 从而达到th文本在初始展示的完整性。
因此在配置宽度时需要参照实际场景, 并建议留下一列做为自适应时的缓冲.
特别注意的是: 所有的列相加大于table所在的容器时，表格将会出现横向滚动条.

#### 想清除当前记忆的宽度及列位置时怎么办?
可使用clear方法,调用方式: GridManager.clear(gridManagerName)

**Comment by snakeUni** [comment]
那个滚动条也是单独写的嘛，好像没找到在哪个文件里。

**Comment by baukh789** [comment]
> 那个滚动条也是单独写的嘛，好像没找到在哪个文件里。

主要的逻辑在这里: `src/module/scroll/index.js`

**Comment by dataobject-org** [comment]
{"column":{"gm_checkbox":{"key":"gm_checkbox","text":"","isAutoCreate":true,"isShow":true,"disableCustomize":true,"width":"40px","index":0,"__width":"40px","__isShow":true},"gm_order":{"key":"gm_order","text":"序号","isAutoCreate":true,"isShow":true,"disableCustomize":true,"width":"50px","index":1,"__width":"50px","__isShow":true},"title":{"key":"title","width":"200px","sorting":"","isShow":true,"index":2,"__width":"200px","__isShow":true}
点击排序后，GridManager.getLocalStorage输出的sorting输出为空，是否应该为ASC 或 DESC

**Comment by baukh789** [comment]
getLocalStorage是获取用于用户记忆功能的，存储初始宽度、当前宽度等相关数据。



---原始邮件---
发件人: "dataobject-org"<notifications@github.com&gt;
发送时间: 2020年5月18日(周一) 晚上8:10
收件人: "baukh789/GridManager"<GridManager@noreply.github.com&gt;;
抄送: "Assign"<assign@noreply.github.com&gt;;"写个程序换个饼"<182209508@qq.com&gt;;
主题: Re: [baukh789/GridManager] GridManager 常见问题汇总 (#144)




 
{"column":{"gm_checkbox":{"key":"gm_checkbox","text":"","isAutoCreate":true,"isShow":true,"disableCustomize":true,"width":"40px","index":0,"__width":"40px","__isShow":true},"gm_order":{"key":"gm_order","text":"序号","isAutoCreate":true,"isShow":true,"disableCustomize":true,"width":"50px","index":1,"__width":"50px","__isShow":true},"title":{"key":"title","width":"200px","sorting":"","isShow":true,"index":2,"__width":"200px","__isShow":true}
 点击排序后，GridManager.getLocalStorage输出的sorting输出为空，是否应该为ASC 或 DESC

**Comment by dataobject-org** [comment]
请问用户调整后的列信息如何读取？用于为每个用户保存离开时的列表状态。发自我的iPhone------------------ 原始邮件 ------------------发件人: 写个程序换个饼  <notifications@github.com>发送时间: 2020年5月18日 20:53收件人: baukh789/GridManager <GridManager@noreply.github.com>抄送: dataobject-org <dataobject@hotmail.com>, Comment <comment@noreply.github.com>主题: 回复：[baukh789/GridManager] GridManager 常见问题汇总 (#144)
getLocalStorage是获取用于用户记忆功能的，存储初始宽度、当前宽度等相关数据。







---原始邮件---

发件人: "dataobject-org"<notifications@github.com&gt;

发送时间: 2020年5月18日(周一) 晚上8:10

收件人: "baukh789/GridManager"<GridManager@noreply.github.com&gt;;

抄送: "Assign"<assign@noreply.github.com&gt;;"写个程序换个饼"<182209508@qq.com&gt;;

主题: Re: [baukh789/GridManager] GridManager 常见问题汇总 (#144)









 

{"column":{"gm_checkbox":{"key":"gm_checkbox","text":"","isAutoCreate":true,"isShow":true,"disableCustomize":true,"width":"40px","index":0,"__width":"40px","__isShow":true},"gm_order":{"key":"gm_order","text":"序号","isAutoCreate":true,"isShow":true,"disableCustomize":true,"width":"50px","index":1,"__width":"50px","__isShow":true},"title":{"key":"title","width":"200px","sorting":"","isShow":true,"index":2,"__width":"200px","__isShow":true}

 点击排序后，GridManager.getLocalStorage输出的sorting输出为空，是否应该为ASC 或 DESC

 

—

You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub, or unsubscribe.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/baukh789/GridManager/issues/144#issuecomment-630162637",
"url": "https://github.com/baukh789/GridManager/issues/144#issuecomment-630162637",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by baukh789** [comment]
如果你想再下次再入进入时，使用上一次用户自已调整的宽度或每页显示条数等信息时，可以通过设置`disableCache: false`来实现。

如果你想拿到实时的列数据，可以通过GridManager.get(table).columnMap获取;

**Comment by FreshFancy** [comment]
你好, 请问分页的位置可以配置在表头上面吗, 自己尝试改了下gm.js, 各种报错, 求教!谢谢!

**Comment by baukh789** [comment]
> 你好, 请问分页的位置可以配置在表头上面吗, 自己尝试改了下gm.js, 各种报错, 求教!谢谢!

当前版本并没有这一类的配置项，你可以通过更改渲染完成的css来实现。

**Comment by FreshFancy** [comment]
你好, 我在Git上直接拉代码自己改渲染模板再打包是吗, 请问有排序的禁用配置吗, 貌似也没看到呢, 不想要排序, 麻烦啦!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baukh789/GridManager"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月16日(星期四) 中午1:20
收件人:&nbsp;"baukh789/GridManager"<GridManager@noreply.github.com&gt;;
抄送:&nbsp;"若水"<975616841@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [baukh789/GridManager] GridManager 常见问题汇总 (#144)





  
你好, 请问分页的位置可以配置在表头上面吗, 自己尝试改了下gm.js, 各种报错, 求教!谢谢!
  
当前版本并没有这一类的配置项，你可以通过更改渲染完成的css来实现。

**Comment by BoWang816** [comment]
> 你好, 我在Git上直接拉代码自己改渲染模板再打包是吗, 请问有排序的禁用配置吗, 貌似也没看到呢, 不想要排序, 麻烦啦!
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "baukh789/GridManager" <notifications@github.com&gt;; 发送时间:&nbsp;2020年7月16日(星期四) 中午1:20 收件人:&nbsp;"baukh789/GridManager"<GridManager@noreply.github.com&gt;; 抄送:&nbsp;"若水"<975616841@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [baukh789/GridManager] GridManager 常见问题汇总 (#144) 你好, 请问分页的位置可以配置在表头上面吗, 自己尝试改了下gm.js, 各种报错, 求教!谢谢! 当前版本并没有这一类的配置项，你可以通过更改渲染完成的css来实现。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

相关配置可以查看API文档：https://gridmanager.lovejavascript.com/api/index.html

**Comment by FreshFancy** [comment]
收到回复,很感谢你抽空解答.&nbsp; 已经按照需求改了分页模板和一些东西. 个人的一点小疑惑(也许是我菜吧, 没掌握好,见笑啦)
1.点击行的时候, 不能方便的获取到当前点击行的DOM元素
2.针对每个单元格点击的时候, 无法将整个row数据作为整个参数传递, 还是要绑定在data-自定义属性上, 如果需要多个的话, 就不是很方便.&nbsp;


此行目的是, 我在拉取的代码上改好了, 怎么打包成单独的js和css文件包呢, 按package.json上&nbsp; npm run build&nbsp; 命令打包错误呢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baukh789/GridManager"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月17日(星期五) 晚上6:30
收件人:&nbsp;"baukh789/GridManager"<GridManager@noreply.github.com&gt;;
抄送:&nbsp;"若水"<975616841@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [baukh789/GridManager] GridManager 常见问题汇总 (#144)





  
你好, 我在Git上直接拉代码自己改渲染模板再打包是吗, 请问有排序的禁用配置吗, 貌似也没看到呢, 不想要排序, 麻烦啦!
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "baukh789/GridManager" <notifications@github.com&gt;; 发送时间:&nbsp;2020年7月16日(星期四) 中午1:20 收件人:&nbsp;"baukh789/GridManager"<GridManager@noreply.github.com&gt;; 抄送:&nbsp;"若水"<975616841@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [baukh789/GridManager] GridManager 常见问题汇总 (#144) 你好, 请问分页的位置可以配置在表头上面吗, 自己尝试改了下gm.js, 各种报错, 求教!谢谢! 当前版本并没有这一类的配置项，你可以通过更改渲染完成的css来实现。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
相关配置可以查看API文档：https://gridmanager.lovejavascript.com/api/index.html

**Comment by BoWang816** [comment]
> 收到回复,很感谢你抽空解答.&nbsp; 已经按照需求改了分页模板和一些东西. 个人的一点小疑惑(也许是我菜吧, 没掌握好,见笑啦) 1.点击行的时候, 不能方便的获取到当前点击行的DOM元素 2.针对每个单元格点击的时候, 无法将整个row数据作为整个参数传递, 还是要绑定在data-自定义属性上, 如果需要多个的话, 就不是很方便.&nbsp; 此行目的是, 我在拉取的代码上改好了, 怎么打包成单独的js和css文件包呢, 按package.json上&nbsp; npm run build&nbsp; 命令打包错误呢
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "baukh789/GridManager" <notifications@github.com&gt;; 发送时间:&nbsp;2020年7月17日(星期五) 晚上6:30 收件人:&nbsp;"baukh789/GridManager"<GridManager@noreply.github.com&gt;; 抄送:&nbsp;"若水"<975616841@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [baukh789/GridManager] GridManager 常见问题汇总 (#144) 你好, 我在Git上直接拉代码自己改渲染模板再打包是吗, 请问有排序的禁用配置吗, 貌似也没看到呢, 不想要排序, 麻烦啦! … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "baukh789/GridManager" <notifications@github.com&gt;; 发送时间:&nbsp;2020年7月16日(星期四) 中午1:20 收件人:&nbsp;"baukh789/GridManager"<GridManager@noreply.github.com&gt;; 抄送:&nbsp;"若水"<975616841@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题:&nbsp;Re: [baukh789/GridManager] GridManager 常见问题汇总 (#144) 你好, 请问分页的位置可以配置在表头上面吗, 自己尝试改了下gm.js, 各种报错, 求教!谢谢! 当前版本并没有这一类的配置项，你可以通过更改渲染完成的css来实现。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. 相关配置可以查看API文档：https://gridmanager.lovejavascript.com/api/index.html — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

如果你是直接clone项目的代码，并自己改了源码，npm run build出现错误的话，就是你自己改的东西出现错误了哦，需要排查一下具体错误是什么。

你如果想要将分页信息调整到表格头部，只需要调整对应的css通过样式设置将页面进行调整，调整后自己打包即可。打包出来的默认文件夹是dist，在下面会有gm.css和gm.js，引入到你的项目即可使用。

**Comment by FreshFancy** [comment]
收到回复,很感谢你抽空解答.&nbsp; 已经按照需求改了分页模板和一些东西. 个人的一点小疑惑(也许是我菜吧, 没掌握好,见笑啦)
1.点击行的时候, 不能方便的获取到当前点击行的DOM元素
2.针对每个单元格点击的时候, 无法将整个row数据作为整个参数传递, 还是要绑定在data-自定义属性上, 如果需要多个的话, 就不是很方便. 


此行目的是, 我在拉取的代码上改好了, 怎么打包成单独的js和css文件包呢, 按package.json上&nbsp; npm run build&nbsp; 命令打包错误呢
打包错误已经解决了, 原因是使用了的eslint-loader导致的, 打扰啦!




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "baukh789/GridManager"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月17日(星期五) 晚上6:30
收件人:&nbsp;"baukh789/GridManager"<GridManager@noreply.github.com&gt;;
抄送:&nbsp;"若水"<975616841@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [baukh789/GridManager] GridManager 常见问题汇总 (#144)





  
你好, 我在Git上直接拉代码自己改渲染模板再打包是吗, 请问有排序的禁用配置吗, 貌似也没看到呢, 不想要排序, 麻烦啦!
 …
 ------------------ 原始邮件 ------------------ 发件人: "baukh789/GridManager" <notifications@github.com&gt;; 发送时间: 2020年7月16日(星期四) 中午1:20 收件人: "baukh789/GridManager"<GridManager@noreply.github.com&gt;; 抄送: "若水"<975616841@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;; 主题: Re: [baukh789/GridManager] GridManager 常见问题汇总 (#144) 你好, 请问分页的位置可以配置在表头上面吗, 自己尝试改了下gm.js, 各种报错, 求教!谢谢! 当前版本并没有这一类的配置项，你可以通过更改渲染完成的css来实现。 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
相关配置可以查看API文档：https://gridmanager.lovejavascript.com/api/index.html

**Comment by lovering-liuzhiqiang** [comment]
你好， 我们的表头数据是和表体数据一个接口返回的，所以我们需要动态表头功能，现在有什么办法么？没有的话 我就要自己改代码啦

**Comment by baukh789** [comment]
@lovering-liuzhiqiang 
你可以使用静态数据模式，在数据获取成功后再进行表格渲染。

**Comment by lovering-liuzhiqiang** [comment]
@baukh789 如果用静态的话，是不是得我们自己写逻辑管理分页

**Comment by FreshFancy** [comment]
你好，columnData数据里面的template函数可以 引用外部定义好的一个函数吗？ 我封装了一个函数，在template里面引用 获取不到title和row的数据




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "baukh789/GridManager"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月29日(星期三) 中午11:45
收件人:&nbsp;"baukh789/GridManager"<GridManager@noreply.github.com&gt;;
抄送:&nbsp;"若水"<975616841@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [baukh789/GridManager] GridManager 常见问题汇总 (#144)





 
@lovering-liuzhiqiang
 你可以使用静态数据模式，在数据获取成功后再进行表格渲染。

**Comment by baukh789** [comment]
@FreshFancy 在template函数中返回外部定义函数的结果即可，所需要的参数可以在template传递至外部定义的函数内。

**Comment by dataobject-org** [comment]
感谢发自我的iPhone------------------ 原始邮件 ------------------发件人: 写个程序换个饼  <notifications@github.com>发送时间: 2020年8月11日 17:01收件人: baukh789/GridManager <GridManager@noreply.github.com>抄送: dataobject-org <dataobject@hotmail.com>, Mention <mention@noreply.github.com>主题: 回复：[baukh789/GridManager] GridManager 常见问题汇总 (#144)
@FreshFancy 在template函数中返回外部定义函数的结果即可，所需要的参数可以在template传递至外部定义的函数内。

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/baukh789/GridManager/issues/144#issuecomment-671823919",
"url": "https://github.com/baukh789/GridManager/issues/144#issuecomment-671823919",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by lovering-liuzhiqiang** [comment]
![image](https://user-images.githubusercontent.com/20617262/90128082-da922600-dd98-11ea-98aa-532018ea08a1.png)
我想把rowObject 传到@click的方法里该怎么办

**Comment by baukh789** [comment]
@lovering-liuzhiqiang 你可以参考下Vue模板的使用方式, 用element-ui的button举个例子:
```
{
     columnData: [
           {
                    key: 'action',
                    text: '操作',
                    width: '100px',
                    align: 'center',

                    // template=> function: return vue template
                    // vue模版中将自动添加row字段，该字段为当前行所使用的数据
                    // vue模版将不允许再使用template函数中传入的参数
                    template:() => {
                        return '<el-button size="mini" type="danger" @click="delRelation(row)">解除绑定</el-button>';
                    }
            }
    ]
}
```
所有使用到模板的地方都可以使用这种方式，如text、topTemplate等。
当然你需要使用vue版本的gridmanager，[详细看这里](https://github.com/baukh789/GridManager-vue)

**Comment by xlx5316** [comment]
Google Chrome 最新版本中 表头与表格明显错位
![image](https://user-images.githubusercontent.com/21599253/92064940-374d9300-edd1-11ea-9534-045192ae2fc0.png)

**Comment by baukh789** [comment]
@xlx5316 你使用[demo](http://develop.lovejavascript.com/node_modules/gridmanager/demo/demo1.html)试一下，我刚在chrome 85.0上试了一下没有复现。

**Comment by xlx5316** [comment]
> @xlx5316 你使用[demo](http://develop.lovejavascript.com/node_modules/gridmanager/demo/demo1.html)试一下，我刚在chrome 85.0上试了一下没有复现。

 😂我使用的demo代码似乎没有问题,这个样式问题是我在这上面
http://develop.lovejavascript.com/node_modules/gridmanager/demo/index.html 
看到的

**Comment by baukh789** [comment]
@xlx5316 我刚发的demo也是这个地址，不过没有复现。你可以把你操作的步骤描述一下吗？我定位下问题的原因

**Comment by xlx5316** [comment]
> @xlx5316 我刚发的demo也是这个地址，不过没有复现。你可以把你操作的步骤描述一下吗？我定位下问题的原因

刚试了下，在调整多列列宽时会出现这个问题

**Comment by baukh789** [comment]
@xlx5316 我刚调整列宽后也没有发现复现该问题，在控制台执行GridManager.version是2.14.2吗？

**Comment by xlx5316** [comment]
> @xlx5316 我刚调整列宽后也没有发现复现该问题，在控制台执行GridManager.version是2.14.2吗？

这可能是分辨率的问题，我尝试把浏览器缩小百分之80之后就复现不了，我的电脑是笔记本的1920 * 1080，我重新试着把浏览器放大问题似乎也会重现
![image](https://user-images.githubusercontent.com/21599253/92067999-4f74e080-edd8-11ea-88c5-0d66f79c6f0c.png)

**Comment by baukh789** [comment]
@xlx5316 感谢，我已经在另一台电脑上定位到问题了下个版本修复该问题

**Comment by baukh789** [comment]
@xlx5316 v2.14.3版本中已经修复该问题，你可以使用原来的方式再试一下。

**Comment by xlx5316** [comment]
> @xlx5316 v2.14.3版本中已经修复该问题，你可以使用原来的方式再试一下。

好的!

**Comment by BBniubility** [comment]
![image](https://user-images.githubusercontent.com/33337177/93978374-7c505e00-fdae-11ea-94c7-4c7117231ece.png)
![image](https://user-images.githubusercontent.com/33337177/93978417-8ffbc480-fdae-11ea-80c9-5f92b04420ee.png)
后面的列全部都不展示了，是我编写的问题还是不支持这么多列？

**Comment by baukh789** [comment]
@BBniubility 
1、当前使用的是哪个框架版本，版本号是否为最新的。
2、如果当前列为较复杂的情况，建议不设置宽度由组件自行匹配。

**Comment by BBniubility** [comment]
@baukh789 
下载的是网站上最新班的框架支持镶嵌表头；
我把所有的宽度设置去掉也无法展示后面的内容

**Comment by baukh789** [comment]
@BBniubility 我排查下

**Comment by baukh789** [comment]
@BBniubility 该问题已修复，更新最新版本可解决。

**Comment by BBniubility** [comment]
@baukh789 感谢老哥，请你喝个咖啡了

**Comment by BBniubility** [comment]
![image](https://user-images.githubusercontent.com/33337177/94217465-a1f77780-ff14-11ea-9dd6-0713bc8f90ed.png)
表头是正确显示了，下面的格式全乱了

**Comment by BBniubility** [comment]
![image](https://user-images.githubusercontent.com/33337177/94218342-de2bd780-ff16-11ea-8c41-b550d4b6ed97.png)
![image](https://user-images.githubusercontent.com/33337177/94218355-e7b53f80-ff16-11ea-9278-457874f5958d.png)
麻烦老哥再看看，这个还是有问题

**Comment by BBniubility** [comment]
![image](https://user-images.githubusercontent.com/33337177/94218445-1501ed80-ff17-11ea-8d5c-ed66f0d63189.png)
![image](https://user-images.githubusercontent.com/33337177/94218474-22b77300-ff17-11ea-8f1f-536e56aa8330.png)
还是有问题麻烦看看

**Comment by baukh789** [comment]
@BBniubility 我看一下

**Comment by baukh789** [comment]
@BBniubility [Version 2.14.9](https://gridmanager.lovejavascript.com/version/index.html)

**Comment by BBniubility** [comment]
@baukh789 我这边还是没有对齐，连最后的表头都是错的。
![image](https://user-images.githubusercontent.com/33337177/94246317-2d412f00-ff4e-11ea-8cbf-2acd742e991f.png)
![image](https://user-images.githubusercontent.com/33337177/94246477-5eb9fa80-ff4e-11ea-9b2d-4798b357d3ac.png)

**Comment by baukh789** [comment]
columnData发一下

**Comment by BBniubility** [comment]
columnData: [
            {
                key: 'OrganizationSubsidiary',
                align: 'center',
                text: '组织/子公司',
            },{
                key: 'PrimarySector',
                text: '一级部门',
            },{
                 key: 'BudgetDirector',
                 text: '预算负责人',
             },{
                key: 'beginningNumber',
                text: '期初人数',
            },{
                key: 'PessoalDosQuadros',
                text: '编制内人员',
                align: 'center',
                 children: [
                     {
                         key: 'OnPersonnel',
                         text: '2019年10月31日在岗人员',
                         align: 'center',
                         children: [
                            {
                                key: 'OnPersonnelbl',
                                text: '保留',
                            },{
                                key: 'OnPersonnelbldc',
                                text: '调出',
                            },{
                                key: 'OnPersonnelbllz',
                                text: '离职',
                            },{
                                key: 'OnPersonnelblxj',
                                text: '小计',
                            }]
                     },{
                        key: 'AlreadySentOffer',
                        text: '已发offer待入职',
                    },{
                        key: 'NewStaff',
                        text: '2020年1月1日起新增人员',
                        align: 'center',
                        children: [
                           {
                               key: 'ClubRecruit',
                               text: '社招',
                               align: 'center',
                               children: [
                                {
                                    key: 'talents',
                                    text: '领军人才',
                                },{
                                    key: 'OtherPersonnel',
                                    text: '其他人员',
                                },{
                                    key: 'ClubRecruitxj',
                                    text: '小计',
                                }]
                           },{
                               key: 'SchoolRecruit',
                               text: '校招',
                               align: 'center',
                               children: [
                                {
                                    key: 'HasThreeSides',
                                    text: '已签三方',
                                },{
                                    key: 'ToRecruit',
                                    text: '待招',
                                },{
                                    key: 'SchoolRecruitxj',
                                    text: '小计',
                                }]
                           },{
                               key: 'CallIn',
                               text: '调入',
                           },{
                               key: 'NewStaffxj',
                               text: '小计',
                           }]
                    },{
                        key: 'PrepareSummary',
                        text: '编制汇总',
                        align: 'center',
                        children: [
                            {
                                key: 'TotalEstablishment',
                                text: '总编制',
                            },{
                                key: 'NetIncrease',
                                text: '净增加',
                            },{
                                key: 'NetRate',
                                text: '净增率',
                            }]
                    },
                 ]
            },{
                key: 'OutsideStaffing',
                text: '编制外人员',
                children: [
                    {
                        key: 'LaborDispatch',
                        text: '劳务派遣',
                    },{
                        key: 'intern',
                        text: '实习生',
                    },{
                        key: 'postdoctoral',    
                        text: '博士后',
                    },{
                        key: 'OutsideStaffingxj',
                        text: '小计',
                    }
                ]
            }
        ]

**Comment by BBniubility** [comment]
@baukh789 麻烦了

**Comment by baukh789** [comment]
@BBniubility V2.14.10，顺便问下，你没有使用vue或react框架吗？

**Comment by BBniubility** [comment]
@baukh789 没有使用

**Comment by BBniubility** [comment]
![image](https://user-images.githubusercontent.com/33337177/94353675-6ee4ed80-00a6-11eb-8855-9877a2c80bb6.png)
我这边还是没有对齐

**Comment by BoWang816** [comment]
> ![image](https://user-images.githubusercontent.com/33337177/94353675-6ee4ed80-00a6-11eb-8855-9877a2c80bb6.png)
> 我这边还是没有对齐

我尝试了你所使用的columnData，并且自己增加了mock数据，是可以完整显示列表与数据的。

![image](https://user-images.githubusercontent.com/26587649/94354073-11eb3680-00aa-11eb-80d6-6dc8d685f7f9.png)

![image](https://user-images.githubusercontent.com/26587649/94354091-4232d500-00aa-11eb-8753-c78164cf3084.png)


mock数据：
![image](https://user-images.githubusercontent.com/26587649/94354101-4eb72d80-00aa-11eb-9b49-41a177ab409b.png)

你也可以先尝试使用我写的mock数据，看是否能正常显示：
使用方式：
```
ajaxData: (setting, params) => {
	// return []
	return 'https://www.fastmock.site/mock/22ba01dad066341d90466f136011020e/blog/table';
}
```

另外你目前截图中数据都是空列，可能也是导致错乱的原因，可以先补齐数据，数据为空是用'--'代替

**Comment by BBniubility** [comment]
好的，我尝试加上数据，但是我的表头有错误，最后几行表头的父子关系都是错的

**Comment by BBniubility** [comment]
![image](https://user-images.githubusercontent.com/33337177/94354394-1cf39600-00ad-11eb-95a9-e37753c2f29a.png)
还是有问题

**Comment by baukh789** [comment]
在本地控制台输出下，GridManager.version 看是否为2.14.10

**Comment by BBniubility** [comment]
是2.14.9，我有替换最新js和css

**Comment by BBniubility** [comment]
我从官网下下来的就是2.14.9版本的

**Comment by baukh789** [comment]
@BBniubility 你重新下载下试试，刚拉了个微信群你可以在这个issues的第一条中通过扫描二维码加入。

**Comment by HEXIAYUE** [comment]
你好   GridManager.resetLayout('demo-baseCode', 'auto', 'auto'); 这个设置高度属性为auto好像不生效。

**Comment by baukh789** [comment]
@HEXIAYUE `GridManager.resetLayout('demo-baseCode', '100%', '100%');`

**Comment by wangrong97111** [comment]
你好，在使用中遇到了问题，还望解答
版本："gridmanager-vue": "^1.7.11",
1.设置height为 100%时，disableCache:false，用户记忆功能无效。
2.height为 100%时，实现表头吸顶功能如何实现（api有莫有这个功能，不设置具体高度然后吸顶的）。

**Comment by baukh789** [comment]
@wang97111 
1.当disableCache: false时，记忆功能失效可能是由于配置项变更导致的。
2.height: 100%时，外部容器需要有height属性。

**Comment by Drunk-Boy** [comment]
支持选中修改背景样式吗？

**Comment by baukh789** [comment]
@Drunk-Boy 选中的行会在tr上新增attribute[checked="true"]，你可以通过操作为这个选择器增加样式来控制背景。  

如果你想通过自定义的class来控制，可以使用[rowRenderHandler](https://gridmanager.lovejavascript.com/api/index.html#rowRenderHandler)中的gm_row_class_name来进行控制。

**Comment by huang160** [comment]
树表格在多选时候，子行能否也有多选按钮可以点击呢，我看案例只能选父层
