### ISSUE TITLE
表格高度过高，或者表格显示条数大于20条数据时，loading遮罩层没有覆盖完整

### ISSUE THREAD

**Issue by pengqian089** [baukh789/GridManager#227]
![示例图](https://user-images.githubusercontent.com/13491546/129374464-0fe0d392-e693-4435-acfa-e6a1b5280530.png)
如图，有解决方法吗？

**Comment by baukh789** [comment]
这个原因可能是所在容器高度设置问题导致的，你可以看下容器高度是否设置正常。
还有这个loading可以通过模板更改样式，你在API上搜一下。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年8月13日(周五) 晚上10:45
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [baukh789/GridManager] 表格高度过高，或者表格显示条数大于20条数据时，loading遮罩层没有覆盖完整 (#227)




 

 如图，有解决方法吗？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by pengqian089** [comment]
> 这个原因可能是所在容器高度设置问题导致的，你可以看下容器高度是否设置正常。 还有这个loading可以通过模板更改样式，你在API上搜一下。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2021年8月13日(周五) 晚上10:45 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [baukh789/GridManager] 表格高度过高，或者表格显示条数大于20条数据时，loading遮罩层没有覆盖完整 (#227) 如图，有解决方法吗？ — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

设置loading模板，添加CSS解决
```css
.gm-loading .loader:before {
    height: 100%;
}
```
通过`GM.showLoading()`调试的时候发现遮罩层实际存在的，before没覆盖完整，目前不知道是那里导致的

**Comment by baukh789** [comment]
你可以使用[loadingTemplate](https://gridmanager.lovejavascript.com/api/index.html#loadingTemplate)进行自定义的loading，连同DOM及CSS都是可以自定义的。
